# Readme

what this section is about.

# Imports and Load Data

In [69]:
## load packages 
import pandas as pd
import re
import numpy as np
import os
import ast

## nltk imports
#!pip install nltk # can install on terminal or by uncommenting this line
import nltk; nltk.download('punkt'); nltk.download('stopwords')
from nltk.tokenize import word_tokenize, wordpunct_tokenize
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

## sklearn imports
from sklearn.feature_extraction.text import CountVectorizer

## lda
from gensim import corpora
import gensim

## visualizing LDA--likely need to install
#!pip install pyLDAvis # can install by uncommenting this line
import pyLDAvis.gensim_models as gensimvis
import pyLDAvis
pyLDAvis.enable_notebook()

## print mult things
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

## random
import random
import string; punctlist = [char for char in string.punctuation] # list of english punctuation marks

[nltk_data] Downloading package punkt to /Users/wyx/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

[nltk_data] Downloading package stopwords to /Users/wyx/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [70]:
df = pd.read_csv("../data/01_cleaned_cases.csv")
df.head()

,case_name,case_type,court,date,case_href,full_text,keywords
0,北京丰冠体育有限公司等与中国滑雪协会等合同纠纷二审民事判决书,民事二审,北京市高级人民法院,2021-12-09,https://wenshu.court.gov.cn/website/wenshu/181...,北京市高级人民法院\n民 事 判 决 书\n（2021）京民终905号\n上诉人（原审被告）...,"['贵司', '新冠', '初心', '信丰', '标准计', '训练场地', '确因', ..."
1,刘慷、吉林省射击射箭运动管理中心人事争议民事再审民事裁定书,民事再审,吉林省高级人民法院,2021-11-05,https://wenshu.court.gov.cn/website/wenshu/181...,吉林省高级人民法院\n民 事 裁 定 书\n（2021）吉民再270号\n再审申请人（一审原...,"['吉体', '劳动厅', '航模', '补上去', '人事厅', '劳动局', '退役费'..."
2,刘小宝、赵效男等买卖合同纠纷民事申请再审审查民事裁定书,民事再审,山东省高级人民法院,2021-07-05,https://wenshu.court.gov.cn/website/wenshu/181...,山东省高级人民法院\n民 事 裁 定 书\n（2021）鲁民申3670号\n再审申请人（一审...,"['历下区', '柴家', '男因', '申号', '海蝶', '万床', '书鲁民', '..."
3,马晓三、云南省人民检察院劳动争议再审民事判决书,民事再审,云南省高级人民法院,2020-06-09,https://wenshu.court.gov.cn/website/wenshu/181...,云南省高级人民法院\n民 事 判 决 书\n（2019）云民再30号\n抗诉机关：云南省人民...,"['省体', '法制报', '云南省人民政府', '奖惩条例', '国家经贸委', '申诉人..."
4,李素萍与北京市木樨园体育运动技术学校劳动争议再审审查与审判监督民事裁定书,民事审判监督,北京市高级人民法院,2020-06-05,https://wenshu.court.gov.cn/website/wenshu/181...,北京市高级人民法院\n民 事 裁 定 书\n（2020）京民申2236号\n再审申请人（一审...,"['人事科', '周润', '体育训练', '意见栏', '表中', '申号', '木樨园'..."

In [71]:
# process into one giant list in preparation for DTM.
corpus = df.keywords.to_list()
corpus[:3] # ramdom check format

["['贵司', '新冠', '初心', '信丰', '标准计', '训练场地', '确因', '专用发票', '赔偿额', '赞助费', '肖像权', '未付', '校际', '公众形象', '风镜', '雪杖', '拒付', '母子公司', '计收', '欠付', '宣传媒体', '下除', '整以', '君泰', '促销品', '下要', '人高学东', '京民', '微信', '需向', '应先', '预期利益', '自本', '天驰', '称案', '高管', '公司法人', '单板', '雪板', '来函', '北京市高级人民法院', '初涉', '同等条件', '食宿费', '赛程', '公司财务', '广告法', '宣传片', '民事判决', '赔偿款']",
 "['吉体', '劳动厅', '航模', '补上去', '人事厅', '劳动局', '退役费', '人王', '绿园区', '现住', '龙运', '慷本', '原省', '机构编制', '销应', '体工队', '工资表', '转递', '工作失误', '扩大会', '民事判决', '在编', '离队', '体委', '民事裁定', '人事处', '合法利益', '调令', '人员名单', '体育局', '体育事业', '离校', '处理意见', '团体冠军', '红头文件', '提审', '公章', '手写', '工作队', '委以', '证据不足', '单方', '名册', '文龙', '开庭审理', '转业', '报批', '偏袒', '开具', '名头']",
 "['历下区', '柴家', '男因', '申号', '海蝶', '万床', '书鲁民', '称有', '工商登记', '市中区', '民事判决', '文化课', '民事裁定', '通济', '调取', '体育局', '带病', '供货', '公司法', '诉讼法', '法律效力', '录音', '涉案', '公示', '受害者', '退役', '占用', '挫折', '商贸', '纺织品', '民事', '注册资本', '不服', '可知', '增资', '办事处', '验证', '缴纳', '法定', '运动员', '资本金', '提交', '出资', '赔偿', '追加', '实质性', '推翻', '当事人', '目录', '无关']"]

# 2. Create a document-term matrix and do some basic diagnostics (more manual approach)

Here we'll create a DTM first using the raw documents; in the activity, you'll create one using the preprocessed docs
that you created in activity 1

## 2.1 Define the dtm function and select data to transform into a document-term matrix

In [72]:
## create DTM function
def create_dtm(list_of_strings, metadata):
    """ 
    Function to create dense document-term matrix (DTM) from a list of strings and provided metadata. 
    A sparse DTM is a list of term_index/doc_index tuples: if a given term occurs in a given doc at least once, 
        then this count is listed as a tuple; if not, that term/doc pair is omitted. 
    In a dense DTM, each row is one text (e.g., an Airbnb listing), each column is a term, and 
        each cell indicates the frequency of that word in that text. 
    
    Parameters:
        list_of_strings (Series): each row contains a preprocessed string (need not be tokenized)
        metadata (DataFrame): contains document-level covariates
    
    Returns:
        Dense DTM with metadata on left and then one column per word in lexicon
    """
    
    # initialize a sklearn tokenizer; this helps us tokenize the preprocessed string input
    vectorizer = CountVectorizer(lowercase = True) 
    dtm_sparse = vectorizer.fit_transform(list_of_strings)
    print('Sparse matrix form:\n', dtm_sparse[:3]) # take a look at sparse representation
    print()
    
    # switch the dataframe from the sparse representation to the normal dense representation (so we can treat it as regular dataframe)
    dtm_dense_named = pd.DataFrame(dtm_sparse.todense(), columns=vectorizer.get_feature_names_out ())
    print('Dense matrix form:\n', dtm_dense_named.head()) # take a look at dense representation
    dtm_dense_named_withid = pd.concat([metadata.reset_index(), dtm_dense_named], axis = 1) # add back document-level covariates

    return(dtm_dense_named_withid)

## 2.2 Execute the dtm function to create the document-term matrix

In [73]:
## example application on raw lowercase texts; 
dtm = create_dtm(list_of_strings = corpus,
                      metadata = df[['case_name', 'case_type', 'court', 'date']])

Sparse matrix form:
 <Compressed Sparse Row sparse matrix of dtype 'int64'
	with 150 stored elements and shape (3, 2026)>
  Coords	Values
  (0, 1795)	1
  (0, 1076)	1
  (0, 389)	1
  (0, 256)	1
  (0, 1182)	1
  (0, 1725)	1
  (0, 1414)	1
  (0, 36)	1
  (0, 1813)	1
  (0, 1821)	1
  (0, 1595)	1
  (0, 1146)	1
  (0, 1185)	1
  (0, 305)	1
  (0, 2006)	1
  (0, 1983)	1
  (0, 959)	1
  (0, 1227)	1
  (0, 1712)	1
  (0, 1211)	1
  (0, 712)	1
  (0, 23)	1
  (0, 1053)	1
  (0, 549)	1
  (0, 242)	1
  :	:
  (2, 1906)	1
  (2, 469)	1
  (2, 986)	1
  (2, 563)	1
  (2, 1498)	1
  (2, 1231)	1
  (2, 1268)	1
  (2, 30)	1
  (2, 516)	1
  (2, 618)	1
  (2, 409)	1
  (2, 2014)	1
  (2, 1551)	1
  (2, 1259)	1
  (2, 1873)	1
  (2, 1801)	1
  (2, 1001)	1
  (2, 372)	1
  (2, 1807)	1
  (2, 1894)	1
  (2, 707)	1
  (2, 999)	1
  (2, 846)	1
  (2, 1394)	1
  (2, 1085)	1

Dense matrix form:
    一分钱  一贵  万床  丈八  三性  上位法  上受  上学  上报  上海市第一中级人民法院  ...  骨质增生  高分  高欢  高管  \
0    0   0   0   0   0    0   0   0   0            0  ...     0   0   0   1
1    0   0   0   0   0    0   0   0   0            0  ...     0   0   0   0
2    0   0   1   0   0    0   0   0   0            0  ...     0   0   0   0
3    0   0   0   0   0    0   0   0   0            0  ...     0   0   0   0
4    0   0   0   0   0    0   0   0   1            0  ...     0   0   0   0

   鲲鹏  麟游  黄村  黄标  默示  龙运
0   0   0   0   0   0   0
1   0   0   0   0   0   1
2   0   0   0   0   0   0
3   0   0   0   0   1   0
4   0   0   0   0   0   0

[5 rows x 2026 columns]

In [74]:
## show first set of rows/cols
dtm.head()

# slice out metadata
dtm.iloc[0:4, 5:]

,index,case_name,case_type,court,date,一分钱,一贵,万床,丈八,三性,...,骨质增生,高分,高欢,高管,鲲鹏,麟游,黄村,黄标,默示,龙运
0,0,北京丰冠体育有限公司等与中国滑雪协会等合同纠纷二审民事判决书,民事二审,北京市高级人民法院,2021-12-09,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1,1,刘慷、吉林省射击射箭运动管理中心人事争议民事再审民事裁定书,民事再审,吉林省高级人民法院,2021-11-05,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,2,刘小宝、赵效男等买卖合同纠纷民事申请再审审查民事裁定书,民事再审,山东省高级人民法院,2021-07-05,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,马晓三、云南省人民检察院劳动争议再审民事判决书,民事再审,云南省高级人民法院,2020-06-09,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,4,李素萍与北京市木樨园体育运动技术学校劳动争议再审审查与审判监督民事裁定书,民事审判监督,北京市高级人民法院,2020-06-05,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

,一分钱,一贵,万床,丈八,三性,上位法,上受,上学,上报,上海市第一中级人民法院,...,骨质增生,高分,高欢,高管,鲲鹏,麟游,黄村,黄标,默示,龙运
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [75]:
# basic summary stats of top words

## summing each col
top_terms = dtm[ dtm.columns[5:] ].sum(axis = 0)

## sorting from most frequent to least frequent
result = top_terms.sort_values(ascending = False)

pd.DataFrame(result).head(10)

       0
体育局   34
诉讼法   25
择业    23
民事判决  20
补发    16
聘用    16
民事裁定  16
补偿费   15
运动队   14
体工队   14

# Unsupervised topic modeling via Gensim

In [76]:
# keywords is stored as str. Make it a list. 
df["keywordsl"] = df.keywords.apply(ast.literal_eval)
df.head()

,case_name,case_type,court,date,case_href,full_text,keywords,keywordsl
0,北京丰冠体育有限公司等与中国滑雪协会等合同纠纷二审民事判决书,民事二审,北京市高级人民法院,2021-12-09,https://wenshu.court.gov.cn/website/wenshu/181...,北京市高级人民法院\n民 事 判 决 书\n（2021）京民终905号\n上诉人（原审被告）...,"['贵司', '新冠', '初心', '信丰', '标准计', '训练场地', '确因', ...","[贵司, 新冠, 初心, 信丰, 标准计, 训练场地, 确因, 专用发票, 赔偿额, 赞助费..."
1,刘慷、吉林省射击射箭运动管理中心人事争议民事再审民事裁定书,民事再审,吉林省高级人民法院,2021-11-05,https://wenshu.court.gov.cn/website/wenshu/181...,吉林省高级人民法院\n民 事 裁 定 书\n（2021）吉民再270号\n再审申请人（一审原...,"['吉体', '劳动厅', '航模', '补上去', '人事厅', '劳动局', '退役费'...","[吉体, 劳动厅, 航模, 补上去, 人事厅, 劳动局, 退役费, 人王, 绿园区, 现住,..."
2,刘小宝、赵效男等买卖合同纠纷民事申请再审审查民事裁定书,民事再审,山东省高级人民法院,2021-07-05,https://wenshu.court.gov.cn/website/wenshu/181...,山东省高级人民法院\n民 事 裁 定 书\n（2021）鲁民申3670号\n再审申请人（一审...,"['历下区', '柴家', '男因', '申号', '海蝶', '万床', '书鲁民', '...","[历下区, 柴家, 男因, 申号, 海蝶, 万床, 书鲁民, 称有, 工商登记, 市中区, ..."
3,马晓三、云南省人民检察院劳动争议再审民事判决书,民事再审,云南省高级人民法院,2020-06-09,https://wenshu.court.gov.cn/website/wenshu/181...,云南省高级人民法院\n民 事 判 决 书\n（2019）云民再30号\n抗诉机关：云南省人民...,"['省体', '法制报', '云南省人民政府', '奖惩条例', '国家经贸委', '申诉人...","[省体, 法制报, 云南省人民政府, 奖惩条例, 国家经贸委, 申诉人, 待岗, 政发, 答..."
4,李素萍与北京市木樨园体育运动技术学校劳动争议再审审查与审判监督民事裁定书,民事审判监督,北京市高级人民法院,2020-06-05,https://wenshu.court.gov.cn/website/wenshu/181...,北京市高级人民法院\n民 事 裁 定 书\n（2020）京民申2236号\n再审申请人（一审...,"['人事科', '周润', '体育训练', '意见栏', '表中', '申号', '木樨园'...","[人事科, 周润, 体育训练, 意见栏, 表中, 申号, 木樨园, 原系, 套改, 京民, ..."

In [77]:
## Step 1: re-tokenize and store in list
## here, i'm doing with the raw random sample of text
## in activity, you should do with the preprocessed texts
text_raw_tokens = [one_text for one_text in df.keywordsl]

## Step 2: use gensim create dictionary - gets all unique words across documents
text_raw_dict = corpora.Dictionary(text_raw_tokens)
raw_len = len(text_raw_dict) # get length for comparison below

### explore first few keys and values
### see that key is just an arbitrary counter; value is the word itself
{k: text_raw_dict[k] for k in list(text_raw_dict)[:5]}


## Step 3: filter out very rare and very common words
## here, i'm using the threshold that a word needs to appear in at least
## 5% of docs but not more than 95%
## this is an integer count of docs so i round
lower_bound = round(df.shape[0]*0.05)
upper_bound = round(df.shape[0]*0.95)

### apply filtering to dictionary
text_raw_dict.filter_extremes(no_below = lower_bound,
                             no_above = upper_bound)
print(f'Filtering out very rare and very common words reduced the \
length of dictionary from {str(raw_len)} to {str(len(text_raw_dict))}.')
{k: text_raw_dict[k] for k in list(text_raw_dict)[:5]} # show first five entries after filtering


## Step 4: apply dictionary to TOKENIZED texts
## this creates a mapping between each word 
## in a specific listing and the key in the dictionary.
## for words that remain in the filtered dictionary,
## output is a list where len(list) == n documents
## and each element in the list is a list of tuples
## containing the mappings
corpus_fromdict = [text_raw_dict.doc2bow(one_text) 
                   for one_text in text_raw_tokens]

### can apply doc2bow(one_text, return_missing = True) to print words
### eliminated from the listing bc they're not in filtered dictionary.
### but feeding that one with missing values to
### the lda function can cause errors
corpus_fromdict_showmiss = [text_raw_dict.doc2bow(one_text, return_missing = True)
                            for one_text in text_raw_tokens]
print('Sample of documents represented in dictionary format (with omitted words noted):')
corpus_fromdict_showmiss[:10]

{0: '下要', 1: '下除', 2: '专用发票', 3: '京民', 4: '人高学东'}

Filtering out very rare and very common words reduced the length of dictionary from 2026 to 228.

{0: '京民', 1: '公司财务', 2: '微信', 3: '欠付', 4: '民事判决'}

Sample of documents represented in dictionary format (with omitted words noted):

[([(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 1), (8, 1)],
  {'下要': 1,
   '下除': 1,
   '专用发票': 1,
   '人高学东': 1,
   '促销品': 1,
   '信丰': 1,
   '公众形象': 1,
   '公司法人': 1,
   '初心': 1,
   '初涉': 1,
   '北京市高级人民法院': 1,
   '单板': 1,
   '同等条件': 1,
   '君泰': 1,
   '天驰': 1,
   '宣传媒体': 1,
   '宣传片': 1,
   '广告法': 1,
   '应先': 1,
   '拒付': 1,
   '整以': 1,
   '新冠': 1,
   '未付': 1,
   '来函': 1,
   '标准计': 1,
   '校际': 1,
   '母子公司': 1,
   '确因': 1,
   '称案': 1,
   '训练场地': 1,
   '贵司': 1,
   '赔偿款': 1,
   '赔偿额': 1,
   '赛程': 1,
   '赞助费': 1,
   '雪杖': 1,
   '雪板': 1,
   '需向': 1,
   '预期利益': 1,
   '风镜': 1,
   '高管': 1}),
 ([(4, 1),
   (9, 1),
   (10, 1),
   (11, 1),
   (12, 1),
   (13, 1),
   (14, 1),
   (15, 1),
   (16, 1),
   (17, 1),
   (18, 1),
   (19, 1),
   (20, 1),
   (21, 1),
   (22, 1),
   (23, 1)],
  {'人员名单': 1,
   '人王': 1,
   '体育事业': 1,
   '偏袒': 1,
   '劳动厅': 1,
   '合法利益': 1,
   '吉体': 1,
   '名册': 1,
   '名头': 1,
   '团体冠军': 1,
   '委以': 1,
   '工作失误': 1,
   '工资表': 1,
   '开具': 1,
   '开庭审理': 1,
   '慷本': 1,
   '手写': 1,
   '扩大会': 1,
   '报批': 1,
   '提审': 1,
   '文龙': 1,
   '机构编制': 1,
   '现住': 1,
   '离校': 1,
   '红头文件': 1,
   '绿园区': 1,
   '航模': 1,
   '补上去': 1,
   '证据不足': 1,
   '调令': 1,
   '转业': 1,
   '转递': 1,
   '销应': 1,
   '龙运': 1}),
 ([(4, 1),
   (13, 1),
   (21, 1),
   (24, 1),
   (25, 1),
   (26, 1),
   (27, 1),
   (28, 1),
   (29, 1)],
  {'万床': 1,
   '书鲁民': 1,
   '供货': 1,
   '公司法': 1,
   '公示': 1,
   '出资': 1,
   '办事处': 1,
   '占用': 1,
   '历下区': 1,
   '受害者': 1,
   '可知': 1,
   '商贸': 1,
   '增资': 1,
   '实质性': 1,
   '工商登记': 1,
   '市中区': 1,
   '带病': 1,
   '当事人': 1,
   '录音': 1,
   '挫折': 1,
   '推翻': 1,
   '提交': 1,
   '文化课': 1,
   '无关': 1,
   '柴家': 1,
   '法定': 1,
   '注册资本': 1,
   '海蝶': 1,
   '涉案': 1,
   '申号': 1,
   '男因': 1,
   '目录': 1,
   '称有': 1,
   '纺织品': 1,
   '缴纳': 1,
   '调取': 1,
   '资本金': 1,
   '赔偿': 1,
   '追加': 1,
   '通济': 1,
   '验证': 1}),
 ([(4, 1),
   (11, 1),
   (17, 1),
   (18, 1),
   (30, 1),
   (31, 1),
   (32, 1),
   (33, 1),
   (34, 1)],
  {'不溯': 1,
   '中共中央办公厅': 1,
   '书向': 1,
   '云体': 1,
   '云南省人民政府': 1,
   '体工': 1,
   '养老保险费': 1,
   '劳办': 1,
   '劳动部': 1,
   '原判': 1,
   '原派': 1,
   '可分性': 1,
   '合同制': 1,
   '回该': 1,
   '国务院令': 1,
   '国家经贸委': 1,
   '奖惩条例': 1,
   '安全卫生': 1,
   '安协': 1,
   '工作证': 1,
   '工资表': 1,
   '抗字': 1,
   '政字': 1,
   '新检民': 1,
   '新闻媒介': 1,
   '昆民': 1,
   '显有': 1,
   '法制报': 1,
   '法民': 1,
   '申诉人': 1,
   '监号': 1,
   '省体': 1,
   '省市区': 1,
   '答辩状': 1,
   '终字': 1,
   '职业技能': 1,
   '职金': 1,
   '费年': 1,
   '进行批评': 1,
   '驳回申诉': 1,
   '默示': 1}),
 ([(0, 1),
   (10, 1),
   (13, 1),
   (21, 1),
   (24, 1),
   (25, 1),
   (27, 1),
   (28, 1),
   (29, 1),
   (31, 1),
   (35, 1),
   (36, 1),
   (37, 1),
   (38, 1),
   (39, 1),
   (40, 1),
   (41, 1),
   (42, 1),
   (43, 1),
   (44, 1),
   (45, 1),
   (46, 1),
   (47, 1),
   (48, 1)],
  {'上报': 1,
   '书京民': 1,
   '争议': 1,
   '事业单位': 1,
   '体育运动': 1,
   '光彩': 1,
   '加盖': 1,
   '北京市高级人民法院': 1,
   '印章': 1,
   '发放': 1,
   '受理': 1,
   '周润': 1,
   '国家机关': 1,
   '套改': 1,
   '工作人员': 1,
   '意见栏': 1,
   '手续': 1,
   '撤销': 1,
   '暂行办法': 1,
   '申号': 1,
   '签署': 1,
   '终所': 1,
   '表中': 1,
   '裁判': 1,
   '认定': 1,
   '证据': 1}),
 ([(49, 1), (50, 1), (51, 1), (52, 1), (53, 1), (54, 1), (55, 1), (56, 1)],
  {'作案工具': 1,
   '侧脑室': 1,
   '全案': 1,
   '判赔': 1,
   '劝回': 1,
   '取物': 1,
   '右额': 1,
   '吧台': 1,
   '塑料箱': 1,
   '处该': 1,
   '大门': 1,
   '存酒': 1,
   '安全部': 1,
   '干粉': 1,
   '库门': 1,
   '开颅': 1,
   '弄碎': 1,
   '指节': 1,
   '挫裂伤': 1,
   '操作间': 1,
   '木柜': 1,
   '杯间': 1,
   '枕部颅': 1,
   '案发时': 1,
   '洋镐': 1,
   '洗手池': 1,
   '洗杯': 1,
   '犯意': 1,
   '监控室': 1,
   '硬膜外': 1,
   '程程': 1,
   '空酒瓶': 1,
   '肩锁': 1,
   '记录表': 1,
   '豪用': 1,
   '起有': 1,
   '超任': 1,
   '超犯': 1,
   '酒吧女': 1,
   '重白': 1,
   '鉴定书': 1,
   '颞部': 1}),
 ([(4, 1),
   (13, 1),
   (21, 1),
   (24, 1),
   (25, 1),
   (27, 1),
   (28, 1),
   (29, 1),
   (33, 1),
   (57, 1),
   (58, 1),
   (59, 1),
   (60, 1),
   (61, 1)],
  {'人事': 1,
   '人力资源': 1,
   '人民政府': 1,
   '代理': 1,
   '代管': 1,
   '优秀': 1,
   '体育教师': 1,
   '农村': 1,
   '分配': 1,
   '发出': 1,
   '变更': 1,
   '天地': 1,
   '安置': 1,
   '实施办法': 1,
   '工资': 1,
   '批准': 1,
   '担任': 1,
   '撤销原判': 1,
   '教育厅': 1,
   '甘民': 1,
   '田心': 1,
   '申号': 1,
   '省市': 1,
   '社会保障': 1,
   '社号': 1,
   '程序': 1,
   '绩效考核': 1,
   '缺少': 1,
   '考核': 1,
   '脱离': 1,
   '自行车': 1,
   '训练': 1,
   '财政厅': 1,
   '适用': 1,
   '通知': 1,
   '顺义': 1}),
 ([(4, 1),
   (8, 1),
   (56, 1),
   (62, 1),
   (63, 1),
   (64, 1),
   (65, 1),
   (66, 1),
   (67, 1),
   (68, 1),
   (69, 1)],
  {'不合格者': 1,
   '专业技能': 1,
   '业务培训': 1,
   '举示': 1,
   '人程': 1,
   '体能训练': 1,
   '体适': 1,
   '保理': 1,
   '保理款': 1,
   '候选者': 1,
   '出庭作证': 1,
   '原始凭证': 1,
   '场地设施': 1,
   '均是由': 1,
   '应否': 1,
   '开户行': 1,
   '批者': 1,
   '承担费用': 1,
   '显失': 1,
   '晶晶': 1,
   '猛方': 1,
   '猛男': 1,
   '确认函': 1,
   '私教': 1,
   '程容': 1,
   '签立': 1,
   '结业证书': 1,
   '考核内容': 1,
   '职业技能': 1,
   '艺术交流': 1,
   '获批': 1,
   '评析': 1,
   '课程内容': 1,
   '负层': 1,
   '败诉方': 1,
   '购买方': 1,
   '赘述': 1,
   '需向': 1,
   '顿开': 1}),
 ([(0, 1),
   (11, 1),
   (15, 1),
   (21, 1),
   (32, 1),
   (39, 1),
   (47, 1),
   (70, 1),
   (71, 1),
   (72, 1),
   (73, 1),
   (74, 1),
   (75, 1),
   (76, 1),
   (77, 1),
   (78, 1),
   (79, 1),
   (80, 1)],
  {'书京民': 1,
   '人事管理': 1,
   '保卫科': 1,
   '北京市人事局': 1,
   '北京市人民政府': 1,
   '司法程序': 1,
   '存续': 1,
   '归队': 1,
   '怠于': 1,
   '政策法规': 1,
   '故张': 1,
   '显属': 1,
   '案一审': 1,
   '欠缴': 1,
   '现张': 1,
   '用工': 1,
   '留用': 1,
   '社会保险费': 1,
   '第二审': 1,
   '简历': 1,
   '管理权': 1,
   '经办': 1,
   '缴付': 1,
   '落款': 1,
   '行政主管': 1,
   '补缴': 1,
   '视同': 1,
   '训练任务': 1,
   '退休年龄': 1,
   '退休金': 1,
   '遗留问题': 1,
   '错位': 1}),
 ([(2, 1),
   (4, 1),
   (63, 1),
   (81, 1),
   (82, 1),
   (83, 1),
   (84, 1),
   (85, 1),
   (86, 1),
   (87, 1)],
  {'中向': 1,
   '义务人': 1,
   '人向': 1,
   '元系': 1,
   '全部都是': 1,
   '公告栏': 1,
   '公证处': 1,
   '写进去': 1,
   '合理合法': 1,
   '处罚金': 1,
   '守信用': 1,
   '履行义务': 1,
   '征信': 1,
   '感谢费': 1,
   '房屋买卖': 1,
   '房款': 1,
   '抵扣': 1,
   '拘传': 1,
   '旅行网': 1,
   '桂民': 1,
   '欠条': 1,
   '民事责任': 1,
   '消费行为': 1,
   '私立学校': 1,
   '罚息': 1,
   '翔同': 1,
   '苇航': 1,
   '要块': 1,
   '计至': 1,
   '责任人员': 1,
   '购房款': 1,
   '赖账': 1,
   '赠予': 1,
   '重合同': 1,
   '金益': 1,
   '铭于': 1,
   '铭则': 1,
   '铭够': 1,
   '铭方': 1,
   '首付款': 1})]

In [78]:
## Step 5: we're finally ready to estimate the model!
## full documentation here - https://radimrehurek.com/gensim/models/ldamodel.html
## here, we're feeding the lda function:
## (1) the corpus we created from the dictionary,
## (2) a parameter we decide on for the number of topics (k),
## (3) the dictionary itself,
## (4) parameter for number of passes through training data (more means slower), and
## (5) parameter that returns, for each word remaining in dict, the topic probabilities.
## see documentation for many other arguments you can vary
ldamod = gensim.models.ldamodel.LdaModel(corpus_fromdict, 
                                         num_topics = 5, 
                                         id2word=text_raw_dict, 
                                         passes=6, 
                                         alpha = 'auto',
                                         per_word_topics = True)

print(type(ldamod))

<class 'gensim.models.ldamodel.LdaModel'>

## Seeing what topics the estimated model discovers

In [79]:
## Post-model 1: explore corpus-wide summary of topics
### getting the topics and top words; can retrieve diff top words
topics = ldamod.print_topics(num_words = 10)
for topic in topics:
    print(topic)

(0, '0.028*"体委" + 0.027*"体工队" + 0.026*"民事判决" + 0.025*"人事厅" + 0.025*"运动队" + 0.021*"在编" + 0.021*"主体资格" + 0.020*"停发" + 0.019*"体育局" + 0.018*"原省"')
(1, '0.018*"专用章" + 0.016*"采购供应" + 0.016*"担为" + 0.016*"猪饲料" + 0.016*"示范园区" + 0.016*"公司财务" + 0.016*"出借" + 0.016*"仔猪" + 0.016*"授权书" + 0.016*"人江光"')
(2, '0.037*"体育局" + 0.035*"择业" + 0.024*"聘用" + 0.022*"补发" + 0.022*"补偿费" + 0.021*"国家体育总局" + 0.019*"运龄" + 0.018*"补偿金" + 0.015*"停发" + 0.015*"退役费"')
(3, '0.037*"诉讼法" + 0.030*"微信" + 0.028*"退役" + 0.025*"民事" + 0.025*"截图" + 0.024*"民事裁定" + 0.020*"律师费" + 0.020*"民法典" + 0.020*"运动员" + 0.018*"民事判决"')
(4, '0.030*"诉讼法" + 0.025*"碑林区" + 0.025*"小学文化" + 0.020*"文文" + 0.020*"无业" + 0.020*"送达" + 0.019*"技术学校" + 0.019*"北京市第二中级人民法院" + 0.019*"体校" + 0.018*"人事科"')

In [80]:
## Post-model 2: explore topics associated with each document
### for each item in our original dictionary, get list of topic probabilities
l=[ldamod.get_document_topics(item) for item in corpus_fromdict]
### print result
text_raw_tokens[0:5]
l[0:5]

[['贵司',
  '新冠',
  '初心',
  '信丰',
  '标准计',
  '训练场地',
  '确因',
  '专用发票',
  '赔偿额',
  '赞助费',
  '肖像权',
  '未付',
  '校际',
  '公众形象',
  '风镜',
  '雪杖',
  '拒付',
  '母子公司',
  '计收',
  '欠付',
  '宣传媒体',
  '下除',
  '整以',
  '君泰',
  '促销品',
  '下要',
  '人高学东',
  '京民',
  '微信',
  '需向',
  '应先',
  '预期利益',
  '自本',
  '天驰',
  '称案',
  '高管',
  '公司法人',
  '单板',
  '雪板',
  '来函',
  '北京市高级人民法院',
  '初涉',
  '同等条件',
  '食宿费',
  '赛程',
  '公司财务',
  '广告法',
  '宣传片',
  '民事判决',
  '赔偿款'],
 ['吉体',
  '劳动厅',
  '航模',
  '补上去',
  '人事厅',
  '劳动局',
  '退役费',
  '人王',
  '绿园区',
  '现住',
  '龙运',
  '慷本',
  '原省',
  '机构编制',
  '销应',
  '体工队',
  '工资表',
  '转递',
  '工作失误',
  '扩大会',
  '民事判决',
  '在编',
  '离队',
  '体委',
  '民事裁定',
  '人事处',
  '合法利益',
  '调令',
  '人员名单',
  '体育局',
  '体育事业',
  '离校',
  '处理意见',
  '团体冠军',
  '红头文件',
  '提审',
  '公章',
  '手写',
  '工作队',
  '委以',
  '证据不足',
  '单方',
  '名册',
  '文龙',
  '开庭审理',
  '转业',
  '报批',
  '偏袒',
  '开具',
  '名头'],
 ['历下区',
  '柴家',
  '男因',
  '申号',
  '海蝶',
  '万床',
  '书鲁民',
  '称有',
  '工商登记',
  '市中区',
  '民事判决',
  '文化课',
  '民事裁定',
  '通济',
  '调取',
  '体育局',
  '带病',
  '供货',
  '公司法',
  '诉讼法',
  '法律效力',
  '录音',
  '涉案',
  '公示',
  '受害者',
  '退役',
  '占用',
  '挫折',
  '商贸',
  '纺织品',
  '民事',
  '注册资本',
  '不服',
  '可知',
  '增资',
  '办事处',
  '验证',
  '缴纳',
  '法定',
  '运动员',
  '资本金',
  '提交',
  '出资',
  '赔偿',
  '追加',
  '实质性',
  '推翻',
  '当事人',
  '目录',
  '无关'],
 ['省体',
  '法制报',
  '云南省人民政府',
  '奖惩条例',
  '国家经贸委',
  '申诉人',
  '待岗',
  '政发',
  '答辩状',
  '体育训练',
  '抗字',
  '费年',
  '默示',
  '职金',
  '新检民',
  '监号',
  '昆民',
  '法民',
  '书向',
  '体工',
  '可分性',
  '终字',
  '政字',
  '原派',
  '不溯',
  '原省',
  '养老保险费',
  '回该',
  '劳办',
  '显有',
  '驳回申诉',
  '安协',
  '合同制',
  '国务院令',
  '工资表',
  '新闻媒介',
  '进行批评',
  '劳动部',
  '原判',
  '民事判决',
  '工作证',
  '在编',
  '省市区',
  '安全卫生',
  '体委',
  '书面通知',
  '云体',
  '中共中央办公厅',
  '补发',
  '职业技能'],
 ['人事科',
  '周润',
  '体育训练',
  '意见栏',
  '表中',
  '申号',
  '木樨园',
  '原系',
  '套改',
  '京民',
  '终所',
  '书京民',
  '北京市高级人民法院',
  '北京市第二中级人民法院',
  '工资待遇',
  '纠纷案件',
  '民事裁定',
  '人事处',
  '体育局',
  '体校',
  '工龄',
  '聘用',
  '加盖',
  '技术学校',
  '诉讼法',
  '暂行办法',
  '印章',
  '体育运动',
  '裁判',
  '国家机关',
  '退役',
  '事业单位',
  '不予',
  '民事',
  '光彩',
  '不服',
  '起诉',
  '上报',
  '受理',
  '运动员',
  '撤销',
  '争议',
  '发放',
  '认定',
  '手续',
  '证据',
  '出生',
  '汉族',
  '签署',
  '工作人员']]

[[(2, np.float32(0.011094728)), (3, np.float32(0.96718085))],
 [(0, np.float32(0.9785353))],
 [(2, np.float32(0.011095505)), (3, np.float32(0.9671804))],
 [(0, np.float32(0.9626035)),
  (2, np.float32(0.0110955015)),
  (3, np.float32(0.012584143))],
 [(3, np.float32(0.6504012)), (4, np.float32(0.33955514))]]

### Visualizing

In [81]:
lda_display = gensimvis.prepare(ldamod, corpus_fromdict, text_raw_dict)
pyLDAvis.display(lda_display)
pprint(lda_model.print_topics())